# Generated by Django 2.1.4 on 2018-12-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_tool_app', '0003_remove_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='id',
            field=models.IntegerField(default=1),
        ),
    ]
